### ISSUE TITLE
Integration manager stuff tries to set up way too early after logging in

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#11090]
```
2019-10-08T16:36:07.439Z I Updating homeserver-configured integration managers...
2019-10-08T16:36:07.441Z E Cannot read property 'credentials' of null
TypeError: Cannot read property 'credentials' of null
    at e.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:1:89674)
    at e.<anonymous> (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:12:66320)
    at E (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:19:91871)
    at Generator._invoke (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:19:91659)
    at Generator.forEach.e.<computed> [as next] (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:19:92051)
    at Generator.c (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:1:81419)
    at f._promiseFulfilled (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:1:38290)
    at e.<anonymous> (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:1:40317)
    at e.<anonymous> (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:12:67489)
    at e.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:12:65746)
    at new e (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:12:65015)
    at Function.value (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:12:65144)
    at Z (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:19:143450)
    at Object.t.setLoggedIn [as onLoggedIn] (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:19:139514)
    at https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:94:193276
    at c (https://riot.im/app/bundles/a6f8076a857e57b3741a/bundle.js:1:81419)
2019-10-08T16:36:07.444Z I setLoggedIn: mxid: @redacted deviceId: redacted guest: false hs: https://redacted softLogout: false
```

**Comment by t3chguy** [comment]
Closing due to no repro in 5 years
