### ISSUE TITLE
Confusing state when using https://app.element.io/#/home without being logged

### ISSUE THREAD

**Issue by bbigras** [element-hq/element-web#14769]
### Description

If I use https://app.element.io/#/home directly without being logged. It shows me as a guest. I can't log out and I don't see a "sign in" button.

This happened to me because for some reason I lost all my Firefox containers, and thus, my cookies.

### Steps to reproduce

- Access https://app.element.io/#/home without a cookie
- Try to log out
- Click the button about not caring about encrypted messages.

Nothing happens.

Logs being sent: yes/no

![image](https://user-images.githubusercontent.com/24027/88486427-6a3b7600-cf4b-11ea-81a9-66815a2d0afb.png)

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: Chrome and Firefox (both latest)
- **OS**: Linux (NixOS)
- **URL**: https://app.element.io/#/home

**Comment by bbigras** [comment]
I can't access the properties to get the logs but I get this in the console:

```
Starting load of AsyncWrapper for modal
index.js:218 GET https://matrix-client.matrix.org/_matrix/client/unstable/room_keys/version 403
(anonymous) @ index.js:218
t @ index.js:179
(anonymous) @ browser-index.js:29
_request @ http-api.js:718
requestOtherUrl @ http-api.js:594
request @ http-api.js:549
authedRequest @ http-api.js:492
A.getKeyBackupVersion @ client.js:1483
_loadBackupStatus @ LogoutDialog.js:55
Dt @ LogoutDialog.js:49
bi @ react-dom.production.min.js:134
Ls @ react-dom.production.min.js:176
_a @ react-dom.production.min.js:263
lc @ react-dom.production.min.js:246
ac @ react-dom.production.min.js:246
Za @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
Wr @ react-dom.production.min.js:123
zr @ react-dom.production.min.js:122
Ya @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
E.setState @ react.production.min.js:12
(anonymous) @ AsyncWrapper.js:54
Promise.then (async)
componentDidMount @ AsyncWrapper.js:46
(anonymous) @ factory.js:665
ia @ react-dom.production.min.js:212
pc @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
hc @ react-dom.production.min.js:248
Za @ react-dom.production.min.js:239
Ya @ react-dom.production.min.js:230
Pc @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tc @ react-dom.production.min.js:240
qc @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
_reRender @ Modal.js:311
createDialogAsync @ Modal.js:222
createDialog @ Modal.js:92
createTrackedDialog @ Modal.js:83
(anonymous) @ UserMenu.tsx:189
a @ react-dom.production.min.js:14
p @ react-dom.production.min.js:14
(anonymous) @ react-dom.production.min.js:14
f @ react-dom.production.min.js:15
st @ react-dom.production.min.js:52
rt @ react-dom.production.min.js:51
at @ react-dom.production.min.js:52
pt @ react-dom.production.min.js:56
L @ react-dom.production.min.js:287
G @ react-dom.production.min.js:19
Jt @ react-dom.production.min.js:70
Xt @ react-dom.production.min.js:69
t.unstable_runWithPriority @ scheduler.production.min.js:19
Vr @ react-dom.production.min.js:122
M @ react-dom.production.min.js:287
$t @ react-dom.production.min.js:68
Show 30 more frames
rageshake.js:65 Unable to fetch key backup status M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
    at https://app.element.io/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:490105
    at https://app.element.io/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:490262
    at Object.callback (https://app.element.io/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:489416)
    at https://app.element.io/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:20760
    at XMLHttpRequest.r.onreadystatechange (https://app.element.io/bundles/2bf2e97955bd40c82b34/vendors~init.js:2:20784)
invariant.js:35 Uncaught (in promise) Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at e.exports (invariant.js:35)
    at i.e.dispatch (Dispatcher.js:167)
    at i.dispatch (dispatcher.ts:44)
    at he (Lifecycle.js:651)
    at Object.ce (Lifecycle.js:528)
    at Object.ID_15 (MatrixChat.tsx:507)
    at i.e._invokeCallback (Dispatcher.js:198)
    at i.e.dispatch (Dispatcher.js:174)
```

**Comment by t3chguy** [comment]
This got fixed
