### ISSUE TITLE
Timeout when joining video room from Element Web

### ISSUE THREAD

**Issue by 0xC0ncord** [element-hq/element-web#22849]
### Steps to reproduce

1. Use a self-hosted Element Web on version 1.11.0.
2. Create a video room and try to join it.
3. Notice the failure to join the room and see this error in the console:
```
Error: Failed to join call in room !BFRzefFLDeastWBIhR:fuwafuwatime.moe: Error: Timed out
    at v.connect (VideoChannelStore.ts:234:19)
    at async onClick (VideoLobby.tsx:172:9)
```

#### What did you expect?

To join the video room.

#### What happened instead?

The join failed without any errors or warnings in the UI.

### Operating system

Gentoo Linux

### Browser information

Google Chrome Version 103.0.5060.53 (Official Build) (64-bit)

### URL for webapp

Private server

### Application version

1.11.0

### Homeserver

Synapse 1.61.1

### Will you send logs?

Yes

**Comment by Kuldran** [comment]
I had this issue and solved it with the following steps

 - make sure registration is enabled in synapse
 - mic and cam (if one exists) must not be used on another application

A mix of both and or one of the two will cause errors but not for all users.

Some error handling should be there when a device is used and let the user know it's in use not error out in panic. This is not a problem for people typically unless you have multiple streaming mediums (discord, and other web recordings going on).

I hope this is helpful for some who run into this.

**Comment by robintown** [comment]
Stale; we've significantly changed how the lobby works since the time of the report. Please open a new issue if you encounter further problems joining calls.
