### ISSUE TITLE
Can't log out of Riot whilst HS is down

### ISSUE THREAD

**Issue by lukebarnard1** [element-hq/element-web#2289]
Trying to log out of my locally-built vector which is logged into a locally-running synapse, but can't open the user settings page in order to do that. Probably because the  settings page loads forever trying to get something from matrix.org.

(And I want to logout so that I can log my local vector onto my own HS)

Seems to be coming from matrix-js-sdk UserSettings.js _renderCryptoInfo.

```
UserSettings.js:335 Error: End-to-end encryption disabled
    at MatrixClient.getStoredDevicesForUser (http://localhost:8083/bundle.js:43252:16)
    at Constructor._renderCryptoInfo (http://localhost:8083/bundle.js:80429:36)
    at Constructor.render (http://localhost:8083/bundle.js:80808:23)
```

**Comment by richvdh** [comment]
I'm surprised this is a thing. If you're logged into a local synapse, why is it trying to reach matrix.org? @lukebarnard1: is it still a thing?

**Comment by lukebarnard1** [comment]
I haven't been in a position where it would happen. I'm not sure why my local, non-federated synapse would be blocked on matrix.org.

**Comment by lukebarnard1** [comment]
From @dbkr:
> Unfortunately, you can't open the settings page because that requires a connection to your HS, so there's no way to log out.

**Comment by gnorbsl** [comment]
I encountered the same issue. It's impossible to logout or open the settings when my synapse server is down.

**Comment by xlith** [comment]
same issue

**Comment by richvdh** [comment]
rereading this, I think the stuff about `matrix.org` is a complete red herring. The report *should* say "the settings page loads forever trying to get something from *the current homeserver*"

**Comment by smokku** [comment]
@richvdh is right. The issue is that _Settings_ page is trying to access current HS.

This makes it impossible to logout and login to some other alive server.

P.S. To work around the issue, you need to clear Local Storage for the web client domain (either through browser privacy settings or DevTools).

**Comment by doug1** [comment]
I just got bit by this one last week.  I had a synapse homeserver instance in a Linux VM for testing, and deleted it when I was done.  My Windows Riot client would just sit there spinning looking for the now non-existent server, and the "logout" button/link was missing from the spinner screen. After waiting (minutes?) for it to time out, I was still not able to use the setting ("gear") icon, since it requires the homeserver to be up to show the settings window.  I then searched the filesystem for a plaintext configuration file where I could change the server name, but only found SQLite and LevelDB files, so no luck there.  In the end, my Riot client install was not easily recoverable, and I was frustrated, so I just deleted it.  Is there any why to recover from a down homeserver at all?  If not, please increase this to P1 since it renders the client unusable.

**Comment by smokku** [comment]
I believe this is fixed in https://riot.im/experimental as there is a "Logout" option accessible directly from user menu.

**Comment by aaronraimist** [comment]
The logging out may be fixed (I haven’t tested that button when the server is down) but `@tango_bravo14:matrix.org` also brought up that you also can’t export your keys if the server is down.

**Comment by varh1i** [comment]
I did:
- kill the riot process
- move your ~/.config/Riot folder to some different location (as backup)
