### ISSUE TITLE
Unable to initialise e2e Cannot read properties of null (reading 'initCrypto')

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#24504]
### Steps to reproduce

Based on this rageshake: https://github.com/matrix-org/element-web-rageshakes/issues/19965

It looks like the user tried to log in with an invalid access token, and then when they tried again the client was broken.

In the logs, first I see:

```
Failed to check for protocol support: will retry MatrixError: [401] Invalid access token passed. (server/_matrix/client/r0/thirdparty/protocols)
M_UNKNOWN_TOKEN: MatrixError: [401] Invalid access token passed. (server/_matrix/client/r0/thirdparty/protocols)
    at c (server/bundles/e944826e9c7d8dd17d52/vendors~init.js:2:1397560)
    at p.requestOtherUrl (server/bundles/e944826e9c7d8dd17d52/vendors~init.js:2:3570904)
```

and then:

```
Failed to call logout API: token will not be invalidated MatrixError: [401] Invalid access token passed. (server/_matrix/client/r0/logout)
M_UNKNOWN_TOKEN: MatrixError: [401] Invalid access token passed. (server/_matrix/client/r0/logout)
    at c (server/bundles/e944826e9c7d8dd17d52/vendors~init.js:2:1397560)
    at p.requestOtherUrl (server/bundles/e944826e9c7d8dd17d52/vendors~init.js:2:3570904)
```

and:

```
Unable to initialise e2e Cannot read properties of null (reading 'initCrypto')
TypeError: Cannot read properties of null (reading 'initCrypto')
    at Object.initClientCrypto (server/bundles/e944826e9c7d8dd17d52/vendors~init.js:2:122650)
```

I don't see any more retries, so perhaps something is going wrong in the retry handling, or perhaps the user interrupted the retry process by logging out.

Either way, we seem to end up with a null Client which we try to call `initCrypto` on.

### Outcome

.

### Operating system

macOS

### Browser information

User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Application version

1.11.19

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Closing due to no repro in over 3 years
