### ISSUE TITLE
Soft crash in WidgetPip when widget is undefined

### ISSUE THREAD

**Issue by andybalaam** [element-hq/element-web#24538]
### Steps to reproduce

We are seeing multiple rageshakes ([a](https://github.com/matrix-org/element-web-rageshakes/issues/19912), [b](https://github.com/matrix-org/element-web-rageshakes/issues/20008), [c](https://github.com/matrix-org/element-web-rageshakes/issues/20009), [d](https://github.com/matrix-org/element-web-rageshakes/issues/20106), [e](https://github.com/matrix-org/element-web-rageshakes/issues/20122)) with stack traces like this:

```
2023-02-14T23:51:31.482Z I Leaving conference call in !nbavnSLAITjVSROKRR:envs.net
2023-02-14T23:51:31.490Z E Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at $d (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~element-web-app.js:2:748206)
    at sa (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3480208)
    at Ws (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3532289)
    at Ol (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3519562)
    at Dl (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3519490)
    at Fl (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3519353)
    at vl (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3516340)
    at vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3466127
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3548935)
    at $i (vector://vector/webapp/bundles/cf6634786fa1e53bbc46/vendors~init.js:2:3465904)
```

I can't decode the stack trace definitively because I can't find that bundle ID, but the attempts I've made have pointed towards matrix-react-sdk/src/components/views/pips/WidgetPip.tsx .

Looking at the code in there, it does look possible that `widget` might be undefined, so unless someone else is able to decode these traces, it seems we should handle the case that `widget` is undefined in `WidgetPip`.

### Will you send logs?

Yes

**Comment by robintown** [comment]
The component in question has been rewritten and I've not heard any reports like this recently, so presuming we fixed it.
