### ISSUE TITLE
`MaxListenersExceededWarning` `Thread.update`

### ISSUE THREAD

**Issue by weeman1337** [element-hq/element-web#24987]
Flooding our logs with these kind of messages doesn't help.
This issue is about to investigate whether there is a problem here.
If not, the number should be increased to something like the expected value + some buffer.

```
rageshake.ts:74 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:216:15)
    at Thread.addListener (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:232:10)
    at Thread.on (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/init.js:24434:18)
    at vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/init.js:7053:13
    at fk (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72416:359)
    at push.Array.concat.exports.unstable_runWithPriority (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72518:343)
    at gg (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72276:325)
    at Oj (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72415:308)
    at Lj (vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72397:50)
    at vector://vector/webapp/bundles/91bd0f0d8a77e4398f82/vendors~init.js:72277:115
```

**Comment by t3chguy** [comment]
This has gone away
