### ISSUE TITLE
Error decrypting video on some gifs/mp4s sent by non element users on various bridges

### ISSUE THREAD

**Issue by gouthamravee** [element-hq/element-web#26023]
### Steps to reproduce

1. Where are you starting? What can you see?
In chats with users who are not using Matrix/Element, bridged through Mautrix-Telegram or Mautrix-Whatsapp

3. What do you click?
Non matrix/element user sends a gif or MP4

Synapse media size option is set to 50MB, file size is less than media size limit. 

#### What did you expect?
Element should show the media inline in the chat

#### What happened instead?
File is received by element says Error Decrypting video. 

### Operating system

Windows 11, Mac, Android

### Application version

Element Desktop, Element Web, Element Android

### How did you install the app?

From website and google playstore

### Homeserver

Personal Synapse Home Server installed through Matrix Ansible Playbook

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2023-08-21T15:18:38.436Z E Unable to download attachment to decrypt it:  MatrixError: [404] Not found [b'gravee.org', b'pEjGlFLDGrCsmQFMWcYIuzoo'] (https://matrix.gravee.org/_matrix/media/r0/download/gravee.org/pEjGlFLDGrCsmQFMWcYIuzoo)
M_NOT_FOUND: MatrixError: [404] Not found [b'gravee.org', b'pEjGlFLDGrCsmQFMWcYIuzoo'] (https://matrix.gravee.org/_matrix/media/r0/download/gravee.org/pEjGlFLDGrCsmQFMWcYIuzoo)
    at c (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1355935)
    at u (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1394613)
    at async s.getFn (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:1300202)
    at async Promise.all (index 0)
    at async P.downloadImage (vector://vector/webapp/bundles/e1d4beacb839288093f6/bundle.js:2:2760248)
```

Looks like an issue with the event, likely the fault of the bridge or your server.

**Comment by richvdh** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/28060
