### ISSUE TITLE
Element-R: panic and outgoing messages stopped after time went backwards

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26416]
~~This didn't seem to have any particular effect, but is troubling nonetheless:~~

```
panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/instant-0.1.12/src/wasm.rs:24:9:
`earlier` cannot be later than `self`.

Stack:

Error
    at push.1407.module.exports.__wbg_new_abda76e883ba8a5f (vector://vector/webapp/bundles/52ca33933beb098de228/37.js:7089:17)
    at wasm://wasm/011935b2:wasm-function[2735]:0x2a1cdc
    at wasm://wasm/011935b2:wasm-function[17665]:0x3fd706
    at wasm://wasm/011935b2:wasm-function[4233]:0x2ff367
    at wasm://wasm/011935b2:wasm-function[13291]:0x3e348b
    at wasm://wasm/011935b2:wasm-function[13290]:0x3e345c
    at wasm://wasm/011935b2:wasm-function[5517]:0x3388c5
    at wasm://wasm/011935b2:wasm-function[2265]:0x27a23a
    at wasm://wasm/011935b2:wasm-function[705]:0x1929f6
    at wasm://wasm/011935b2:wasm-function[3295]:0x2c941e
```

**Comment by richvdh** [comment]
In #26417, this caused outgoing requests to stop happening.

**Comment by richvdh** [comment]
Looking at a rageshake that includes this panic, it looks like time went backwards:

```
2023-10-23T09:02:30.278Z D FetchHttpApi: --> GET https://matrix.sw1v.org/_matrix/client/v3/sync?filter=xxx&timeout=xxx&since=xxx
2023-10-23T09:02:28.655Z D FetchHttpApi: <-- GET https://matrix.sw1v.org/_matrix/client/v3/sync?filter=xxx&timeout=xxx&since=xxx [-1623ms 200]
2023-10-23T09:02:28.698Z E panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/instant-0.1.12/src/wasm.rs:24:9:
`earlier` cannot be later than `self`.
```

(It looks like this happened when systemd synced my clock:

```
Oct 23 10:02:28 xps9320 systemd-timesyncd[1431]: Initial synchronization to time server 91.189.91.157:123 (ntp.ubuntu.com).
```
)

**Comment by richvdh** [comment]
This seems to be because the polyfill we use for `std::time::Instant` (https://github.com/sebcrozet/instant) uses `Date.now()` rather than a proper monotonic time like `std::time::Instant` says we should.

I have filed an issue (https://github.com/sebcrozet/instant/issues/53)

**Comment by richvdh** [comment]
XKCD particularly on-point today: https://xkcd.com/2867/

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/3961 has upgraded the rust sdk, so this should now be fixed.
