### ISSUE TITLE
[Disabled] Flaky Playwright test: `Threads > should be usable for a conversation`

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26452]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6642883792/job/18048683069#step:8:2216

```
  1) Threads
       should be usable for a conversation:
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'shouldAttemptDecryption')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at MatrixClient.decryptEventIfNeeded (http://localhost:8080/bundles/5c677ee9ac7c78c6c469/bundle.js:16628:15)
      at <unknown> (http://localhost:8080/bundles/5c677ee9ac7c78c6c469/element-web-app.js:39579:14)
      at Array.forEach (<anonymous>)
      at TimelinePanel_TimelinePanel.getEvents (http://localhost:8080/bundles/5c677ee9ac7c78c6c469/element-web-app.js:39577:64)
      at <unknown> (http://localhost:8080/bundles/5c677ee9ac7c78c6c469/element-web-app.js:38601:18)
```

Looks like `TimelineWindow.getEvents` returned an undefined value?

**Comment by richvdh** [comment]
Previously this test failed with a different error: https://github.com/vector-im/element-web/issues/23438

**Comment by dbkr** [comment]
This has just flaked for me (kicking my js-sdk PR out of the merge queue) and accordingly has reached its two strikes.
