### ISSUE TITLE
Element-R: doesn't work in release builds

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#26714]
If you build element-web in release mode, then all the crypto stuff fails with errors like this in the console:

```
Failed to process events on room !UCnwUWwIKhcpaPTHtR:sw1v.org: Error: Expect an `UserId` instance, received `HI` instead
    at A.exports.__wbindgen_error_new (matrix_sdk_crypto_wasm.js:7299:17)
    at <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next::h6cf6c79f3d0e5044 (015888c2:0x3039c5)
    at <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h1a067385358156a8 (015888c2:0x23d53c)
    at matrix_sdk_crypto_wasm::machine::user_ids_to_owned_user_ids::hd597160fad090b65 (015888c2:0x2cd655)
    at olmmachine_updateTrackedUsers (015888c2:0x26d0bf)
    at PA.updateTrackedUsers (matrix_sdk_crypto_wasm.js:3454:18)
    at i.onRoomMembership (RoomEncryptor.ts:98:29)
    at r.onRoomMembership (rust-crypto.ts:1441:13)
    at o.emit (events.js:153:5)
    at Me.emit (typed-event-emitter.ts:89:22)
```

This is due to https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/51.

**Comment by bseclier** [comment]
Same problem here on a fresh Element install. 
Thank you for reporting this issue.

**Comment by Hywan** [comment]
PR is ready. Just need a final polish. Will do it soon.

**Comment by Hywan** [comment]
Can we close this issue since https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/51 has been closed by https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/82?

**Comment by t3chguy** [comment]
@Hywan no since the version of matrix-sdk-crypto-wasm has not yet been updated.

**Comment by richvdh** [comment]
This is now fixed!
