### ISSUE TITLE
ElementR: Reset everything if forgot passphrase does not reset the backup

### ISSUE THREAD

**Issue by BillCarsonFr** [element-hq/element-web#26717]
## Step to reproduce

1. Create an account and setup recovery
2. Logout

3. Login again with this account
4. When asked to verify select "verify with passphrase"
5. Click on forgot passphrase and reset everything
6. Complete the flow (use a passphrase, re-auth)

## Acutal

The old backup is still the current one, and you don't have the key
=> Creates a desynced 4S situation

<img width="573" alt="image" src="https://github.com/vector-im/element-web/assets/9841565/83c2f8b7-169e-4231-9fb4-b96e6cab7363">

Connect this session will fail as it will try to get the backup decryption key from 4S and it's not there.
ALso there is that in logs
```
rageshake.ts:77 TypeError: Reflect.get called on non-object
    at Reflect.get (<anonymous>)
    at matrix_sdk_crypto_wasm.js:8274:1
    at handleError (matrix_sdk_crypto_wasm.js:330:1)
    at module.exports.__wbg_get_97b561fb56f034b5 (matrix_sdk_crypto_wasm.js:8273:58)
    at js_sys::Reflect::get::h49482ab833783b5d (01551216:0x32dfd6)
    at js_sys::try_iter::h60031c3cef7d60b3 (01551216:0x23b0ca)
    at vodozemac::types::curve25519::_::<impl serde::de::Deserialize for vodozemac::types::curve25519::Curve25519PublicKey>::deserialize::he56edfd0b83c9705 (01551216:0x2ba683)
    at olmmachine_importBackedUpRoomKeys (01551216:0xa2224)
    at OlmMachine.importBackedUpRoomKeys (matrix_sdk_crypto_wasm.js:4145:1)
    at RustBackupManager.importBackedUpRoomKeys (backup.ts:209:31)
```

## Expected

Should have reset backup also

**Comment by uhoreg** [comment]
Tracing through the code, it looks like this is because the reset code only calls `bootstrapCrossSigning` and not `bootstrapSecretStorage` (why do we have two functions?). Which means that this looks like it's an issue with current Element Web too. But looking through the react-sdk, it looks like there are a few places where it calls `bootstrapCrossSigning` and not `bootstrapSecretStorage`, so I'll go through those and check which places should be calling both.

**Comment by uhoreg** [comment]
Fixed by https://github.com/matrix-org/matrix-js-sdk/pull/3976/
