### ISSUE TITLE
Retrying unsent edits fails

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26778]
### Steps to reproduce

1. Send a bunch of messages, and edit one of them
2. Encryption is slow due to ER problems so they all queue up
3. Eventually something times out and they 'go red' and fail
4. Hit retry
5. Message sending fails immediately:

```
rageshake.ts:77 Error sending event M_UNKNOWN: MatrixError: [400] Can't send relation to unknown event (https://matrix-client.matrix.org/_matrix/client/v3/rooms/!UcgyhoigetVICUfvRw%3Amatrix.org/send/m.room.encrypted/m1702728156543.1)
    at parseErrorResponse (vector://vector/webapp/bundles/eee97dbd860b28d038a2/bundle.js:129586:12)
    at MatrixHttpApi.requestOtherUrl (vector://vector/webapp/bundles/eee97dbd860b28d038a2/bundle.js:129936:13)
    at async MatrixHttpApi.authedRequest (vector://vector/webapp/bundles/eee97dbd860b28d038a2/bundle.js:129777:24)
    at async MatrixScheduler.procFn (vector://vector/webapp/bundles/eee97dbd860b28d038a2/bundle.js:102961:21)
```

#### What did you expect?
Unsent edits should queue correctly, rather than silently break the retry mechanism.  I'm fairly sure this used to work.

### Application version

Element Nightly version: 2023121601 Crypto version: Rust SDK 0.6.0 (438880a), Vodozemac 0.5.0

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by BillCarsonFr** [comment]
Same cause of this https://github.com/element-hq/element-web/issues/26684
edit is sent before original
