### ISSUE TITLE
Restoring from online backup failed with: "missing field: `sender_claimed_keys`"

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-web#26774]
### Steps to reproduce

1. Import 420,000 keys from my online backup into EWR nightly now that https://github.com/element-hq/element-web/issues/26488 is hopefully fixed.

Takes about 2m to return the https://matrix-client.matrix.org/_matrix/client/v3/room_keys/keys?version=2 req, which looks complete and promising.

However, it then starts rapidly requesting lots of keys for specific sessions from the server - it's as if it's not actually getting them from the ~300MB download it just pulled from the server?

At some point it craps out with...

```
rageshake.ts:77 Error restoring backup Error: missing field `sender_claimed_keys`
    at module.exports.__wbindgen_error_new (matrix_sdk_crypto_wasm.js:7273:1)
    at serde_wasm_bindgen::error::Error::new::haa52582176c8e8a7 (0156008e:0x346ed8)
    at byn$mgfn-shared$serde::de::Error::missing_field::hcb818cd6c817fdc6 (0156008e:0x3d85d6)
    at serde::de::Error::missing_field::hcb818cd6c817fdc6 (0156008e:0x3013a0)
    at olmmachine_importBackedUpRoomKeys (0156008e:0xc3cd7)
    at OlmMachine.importBackedUpRoomKeys (matrix_sdk_crypto_wasm.js:4115:1)
    at RustBackupManager.importBackedUpRoomKeys (backup.ts:209:31)
    at RustCrypto.importBackedUpRoomKeys (rust-crypto.ts:1200:41)
    at MatrixClient.restoreKeyBackup (client.ts:3971:34)
    at async RestoreKeyBackupDialog.tsx:231:17
```

...and it only seems to have processed around 1,700 keys.

#### What did you expect?

Restoring from online backup to work.

#### What happened instead?

Looks like it's being too strict on the keys in the backup?  and/or it's not actually processing the keys it got from the server?

Meanwhile, trying to restore from offline backup in EWR immediately 'Aw snap's the tab, presumably due to OOM.

### Application version

Element version: e9f0a8cddc19-react-de5931d5a8e5-js-68898aeff2c5 Crypto version: Rust SDK 0.6.0 (438880a), Vodozemac 0.5.0

### Will you send logs?

Yes

**Comment by richvdh** [comment]
This is not yet fixed because element has not yet been updated to a sufficiently recent version of matrix-sdk-crypto-wasm.

**Comment by uhoreg** [comment]
I don't think https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/92 is related to this, because key backups don't use the `EncryptionAlgorithm` class.  It just passes the raw JSON to the OlmMachine.

**Comment by uhoreg** [comment]
The relevant PRs are merged now, so this should be fixed now
