### ISSUE TITLE
"Something went wrong" while verifying with another user

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27314]
STR are unclear. Probably involves having multiple verification requests in flight and receiving another.

In the logs:

```
2024-04-10T09:04:34.495Z E VerificationRequest: inner phase == Transitioned but no verifier!
Error: VerificationRequest: inner phase == Transitioned but no verifier!
    at get phase (vector://vector/webapp/bundles/9143bb6191ca2453220f/865.js:1055:17)
    at get pending (vector://vector/webapp/bundles/9143bb6191ca2453220f/865.js:1071:24)
    at UserInfo (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:238295:52)
    at Ch (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307195:137)
    at li (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307218:154)
    at ck (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307307:343)
    at bk (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:347)
    at ak (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:278)
    at Tj (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:138)
    at Lj (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307281:163)
2024-04-10T09:04:34.502Z E VerificationRequest: inner phase == Transitioned but no verifier!
Error: VerificationRequest: inner phase == Transitioned but no verifier!
    at get phase (vector://vector/webapp/bundles/9143bb6191ca2453220f/865.js:1055:17)
    at get pending (vector://vector/webapp/bundles/9143bb6191ca2453220f/865.js:1071:24)
    at UserInfo (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:238295:52)
    at Ch (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307195:137)
    at li (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307218:154)
    at ck (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307307:343)
    at bk (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:347)
    at ak (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:278)
    at Tj (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307288:138)
    at Lj (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:307281:163)
2024-04-10T09:04:34.502Z E The above error occurred while React was rendering the following components: 
    at UserInfo (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:238239:7)
    at aside
    at RightPanel (vector://vector/webapp/bundles/9143bb6191ca2453220f/element-web-app.js:34077:5)
    at div
    at Resizable (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:94214:28)
    at div
    at MainSplit (vector://vector/webapp/bundles/9143bb6191ca2453220f/element-web-app.js:19545:5)
    at ErrorBoundary (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:222540:5)
    at div
    at RoomView (vector://vector/webapp/bundles/9143bb6191ca2453220f/element-web-app.js:44261:5)
    at div
    at div
    at div
    at LoggedInView (vector://vector/webapp/bundles/9143bb6191ca2453220f/element-web-app.js:48158:5)
    at Provider (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:329737:28)
    at $a093c7e1ec25a057$export$f78649fb9ca566b8 (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:336039:29)
    at ErrorBoundary (vector://vector/webapp/bundles/9143bb6191ca2453220f/bundle.js:222540:5)
    at MatrixChat (vector://vector/webapp/bundles/9143bb6191ca2453220f/element-web-app.js:70065:5)
```

**Comment by richvdh** [comment]
Closing this, since we have no useful information about *what* went wrong, so this isn't a useful thing to have in the backlog
