### ISSUE TITLE
Messages not sent and sync stopped

### ISSUE THREAD

**Issue by hughns** [element-hq/element-web#27385]
### Steps to reproduce

I will add a screenshot to the rageshake to show context.

Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

#### What did you expect?

The messages to be sent as normal.

#### What happened instead?

The messages didn't send. And it looks like I've stopped receiving messages too.

### Operating system

macOS

### Application version

Element Nightly version: 2024042301; Crypto version: Rust SDK 0.7.0 (61b175b), Vodozemac 0.5.1

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by hughns** [comment]
It repeats itself after a restart. I'm pretty sure it happened on the previous nightly I had installed (although I'm not sure what version that was).

**Comment by hughns** [comment]
I'm trying to submit debug logs but it appears to be hanging:

<img width="918" alt="image" src="https://github.com/element-hq/element-web/assets/6955675/6bdd0abe-56fd-4858-86c5-ce80f3a02709">

**Comment by rkfg** [comment]
I want to add my input, maybe it would be useful. I have Element deployed as a web app on my own server, I build it from source and just rsync there. In fact, I have two Elements and two Synapses, one is a semi-public instance on the internet, the other is at work. The Element instances are exactly the same, I update them both at the same time. The Synapse versions are slightly different (I use Docker for the internet one and the apt repo for work) but it's probably not very important.

I noticed that the work version started losing sync a few weeks ago. I open the browser console and there are no `sync` requests at all. In the log (rageshake) there's absolutely nothing when they stop. Multiple successful long polling syncs and then just nothing except a few TURN requests. The app still works, I can switch between the tabs, there's no "offline" message, but no new events arrive, obviously. I can still send messages. Hitting F5 helps until the next random sync "crash". The internet instance doesn't suffer from that despite being open next to the work one, in the same browser. Clearing the app data (local storage, indexeddb etc.) didn't fix the issue. So I finally thought, what if it's the server? And maybe it is, though it shouldn't be able to crash the sync loop on the client. What I discovered was this in Synapse log:
```
2025-03-21 11:02:01,800 - twisted - 279 - CRITICAL - sentinel - 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 269, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 285, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/usr/lib/python3/dist-packages/synapse/util/gai_resolver.py", line 164, in get
    return self._getaddrinfo(
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy
```
I have no idea why this exception can happen and a quick google search didn't reveal anything specific. Some suggest it's an inotify issue but I have a very high limit for that. Another suggestion is that it's a file handles limit, but I checked `/proc/<pid>/limits` and it says `Max open files            524288`, and the other numbers are either a few hundred thousands or "unlimited". Also highly unlikely.

So just in case I added more DNS servers in /etc/resolv.conf. This message seems to have disappeared, Element doesn't seem to stop syncing but I need more time to make sure. Synapse version is `1.121.0-5`, installed from the official Debian testing repo.

Possible causes could be some weird URLs being resolved, which use local domain names as the only NS I had specified was 8.8.8.8. Still, it definitely shouldn't stop Element from syncing forever until it's reloaded.

**Comment by rkfg** [comment]
Unfortunately, this didn't help and the problem still happens. I sent the logs though I don't think they're useful.
