### ISSUE TITLE
Element-R: migration to rust failed with "Unable to load session" error

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#27423]
From the logs:

```
2024-04-26T07:38:33.368Z I Migrating data from legacy crypto store. 3033 olm sessions and 30760 megolm sessions to migrate.
2024-04-26T07:38:33.371Z I Migrating data from legacy crypto store. Step 1: base data
2024-04-26T07:38:33.385Z D FetchHttpApi: --> GET https://matrix.org/_matrix/client/v3/room_keys/version
2024-04-26T07:38:33.608Z D FetchHttpApi: <-- GET https://matrix.org/_matrix/client/v3/room_keys/version [223ms 200]
2024-04-26T07:38:33.618Z E Unable to load session The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
TypeError: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
    at c (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:3206555)
    at l.from (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:3212961)
    at a (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:471696)
    at a (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:612401)
    at async kA (vector://vector/webapp/bundles/ad882b5866028f8f562c/5484.js:1:8044606)
    at async vector://vector/webapp/bundles/ad882b5866028f8f562c/5484.js:1:8042627
    at async MA (vector://vector/webapp/bundles/ad882b5866028f8f562c/5484.js:1:8041586)
    at async Module.yA (vector://vector/webapp/bundles/ad882b5866028f8f562c/5484.js:1:8045905)
    at async De.initRustCrypto (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:507070)
    at async Object.initClientCrypto (vector://vector/webapp/bundles/ad882b5866028f8f562c/bundle.js:2:1623288)
```

**Comment by kegsay** [comment]
@BillCarsonFr says this is fixed by https://github.com/matrix-org/matrix-js-sdk/pull/4168

**Comment by richvdh** [comment]
oh, so this is a duplicate of https://github.com/element-hq/element-desktop/issues/1603
