### ISSUE TITLE
Rageshake crash: Cannot read properties of null (reading 'compareDocumentPosition')

### ISSUE THREAD

**Issue by kegsay** [element-hq/element-web#27503]
### Steps to reproduce

Unknown. Seen this in several rageshakes over the past day or so.

### Outcome

```
2024-05-27T19:29:48.045Z E Cannot read properties of null (reading 'compareDocumentPosition')
TypeError: Cannot read properties of null (reading 'compareDocumentPosition')
    at b (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:1767211)
    at Array.sort (<anonymous>)
    at E (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:1767528)
    at Object.ds [as useReducer] (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4262077)
    at t.useReducer (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4373779)
    at x (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:1768580)
    at ss (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4260849)
    at qs (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4270347)
    at Wa (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4313712)
    at Dl (vector://vector/webapp/bundles/f5d0ab2818fe44be0c86/bundle.js:2:4300085)
```

### Application version

1.11.67

### Will you send logs?

Yes

**Comment by glungtung** [comment]
Hello, 
I'd like to complete when you say "Steps to reproduce : unknown", for me it crashes 100% each time when I fold/unfold spaces with subspaces, like steps described in #27532 
Thanks

**Comment by dbkr** [comment]
I can repro this on a regular desktop build, so it's not specific to a third-party packaging of Element.
