### ISSUE TITLE
Cannot log into Element

### ISSUE THREAD

**Issue by chipuni** [element-hq/element-web#27516]
### Steps to reproduce

1. I visited https://element.qoto.org/#/home
2. I immediately got the message:

Something went wrong!
Please [create a new issue](https://github.com/vector-im/element-web/issues/new) on GitHub so that we can investigate this bug.

If you've submitted a bug via GitHub, debug logs can help us track down the problem. Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages.

#### What did you expect?

I expected to see the Matrix server.

#### What happened instead?

I got the message "Something went wrong!
Please [create a new issue](https://github.com/vector-im/element-web/issues/new) on GitHub so that we can investigate this bug.

If you've submitted a bug via GitHub, debug logs can help us track down the problem. Debug logs contain application usage data including your username, the IDs or aliases of the rooms or groups you have visited and the usernames of other users. They do not contain messages."

### Operating system

NixOS Linux

### Browser information

Chromium Version 123.0.6312.122 (Official Build, ungoogled-chromium) (64-bit)

### URL for webapp

https://element.qoto.org/#/home

### Application version

Element version: 6d46ed808231-react-6d46ed808231-js-6d46ed808231 olm version: 3.2.3

### Homeserver

qoto.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Chrome 123 is not supported as per https://github.com/element-hq/element-web#supported-environments

Your Chrome version seems to be blocking Canvas access which is required.

```
2024-06-03T21:45:06.923Z E Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. (SecurityError | 18) 
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:626733
    at Object.l (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:626749)
    at t.a (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:340433)
    at na (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2276580)
    at Gs (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2329016)
    at wc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2316028)
    at Ec (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2315956)
    at yc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2315819)
    at hc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2312806)
    at https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2262475
2024-06-03T21:45:06.924Z E Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported. (SecurityError | 18) 
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:626733
    at Object.l (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:626749)
    at t.a (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:340433)
    at na (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2276580)
    at Gs (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2329016)
    at wc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2316028)
    at Ec (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2315956)
    at yc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2315819)
    at hc (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2312806)
    at https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2262475
2024-06-03T21:45:06.924Z E The above error occured while React was rendering the following components: 
    at t.a (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:339460)
    at span
    at div
    at div
    at d (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:198526)
    at d (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:1472279)
    at at (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:4915810)
    at div
    at aside
    at div
    at Nt (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:4938498)
    at div
    at div
    at Xn (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:4981535)
    at o (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:1267270)
    at Te (https://element.qoto.org/bundles/e31a11df6e868a022f56/vendors~init.js:2:2113045)
```
