### ISSUE TITLE
Unable to restore session

### ISSUE THREAD

**Issue by florianduros** [element-hq/element-web#27666]
### Steps to reproduce

Refreshed develop and went against:

<img width="812" alt="image" src="https://github.com/element-hq/element-web/assets/2621378/268ec56b-8d2b-456a-985c-d17d7526718a">

Error in console
```
Warning! Not using an encryption key for rust crypto store.
...
Unable to load session Error: Error: invalid type: string "8", expected u64
    at module.exports.__wbindgen_error_new (index.js:9754:1)
    at matrix_sdk_crypto_wasm.wasm.<wasm_bindgen::JsError as core::convert::From<E>>::from::h8775e916ccaf4e7e (matrix_sdk_crypto_wasm.wasm-0173b296:0x2bbcb7)
    at matrix_sdk_crypto_wasm.wasm.matrix_sdk_crypto_wasm::machine::OlmMachine::init_helper::{{closure}}::h89bc52bc32d75063 (matrix_sdk_crypto_wasm.wasm-0173b296:0x3f5f6)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h7e45e671070e31cd (matrix_sdk_crypto_wasm.wasm-0173b296:0x1143f8)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h8ef579ea9b649d7d (matrix_sdk_crypto_wasm.wasm-0173b296:0x39387d)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen::convert::closures::invoke1_mut::hd46bf1dda4ab89c1 (matrix_sdk_crypto_wasm.wasm-0173b296:0x3a319b)
    at __wbg_adapter_65 (index.js:278:1)
    at real (index.js:220:1)
```

### Application version

develop

### Will you send logs?

Yes

**Comment by richvdh** [comment]
This happens when (for historical reasons) the indexeddb cryptostore is unencrypted.

**Comment by richvdh** [comment]
Introduced by https://github.com/matrix-org/matrix-rust-sdk/pull/3645

**Comment by t3chguy** [comment]
@richvdh given that PR is only 3h old, are you sure it blocks the current release cycle rather than the next?

**Comment by richvdh** [comment]
yes. It was backported into the current release: https://github.com/matrix-org/matrix-js-sdk/pull/4297

**Comment by t3chguy** [comment]
Thanks for clarifying
