### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by qqubes** [element-hq/element-web#27869]
### Steps to reproduce

The sequence of screenshots demonstrates what happens when I try to log in.
![element_io-1_2024-07-29_10-46-06](https://github.com/user-attachments/assets/41dc29e4-30cf-4865-9ec3-98e1298bde26)
![element_io-2_2024-07-29_10-47-14](https://github.com/user-attachments/assets/61702c2a-fd7c-4f45-a5a1-d12b9e7ce724)
![element_io-3_2024-07-29_10-58-49](https://github.com/user-attachments/assets/ead821c8-e762-4983-98fd-249ec7e5c887)
![element_io-4_2024-07-29_10-59-29](https://github.com/user-attachments/assets/32600028-7204-4dfa-a482-dd61b0e4a8b5)
![element_io-5_2024-07-29_10-59-58](https://github.com/user-attachments/assets/29e18990-2c8f-4bb1-8fed-8c83386e1d1d)
![element_io-6_2024-07-29_11-01-08](https://github.com/user-attachments/assets/01a9de67-3540-4284-bfe3-aa569cc46541)

Afterwards, it gets stuck waiting endlessly for logout.

#### What did you expect?

To login as usual.

#### What happened instead?

Cannot.

### Operating system

qubes OS

### Browser information

Chromium Version 120.0.6099.224 (Official Build) built on Debian 11.8, running on Debian 11.9 (64-bit)

### URL for webapp

app.element.io

### Application version

browser

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by qqubes** [comment]
Worked after restarting the computer.

**Comment by qqubes** [comment]
The issue has recurred. 

I cannot restart my computer everytime I want to log into Matrix.

**Comment by t3chguy** [comment]
> Will you send logs?
Yes

Not seeing any logs from you

**Comment by qqubes** [comment]
I see what happens:

When I try to log in it gets stuck (see Screenshot 3 above). Then if I get tired of waiting an reload the page, I get to Screenshot 4. 

But then when I choose Send Logs, it gives the error: 

> Failed to send logs: No connected database

Btw, I this is using a web browser. I can log in using my Android device.

**Comment by richvdh** [comment]
getting stuck during login sounds somewhat like https://github.com/element-hq/element-web/issues/25779.

If sending logs via the application doesn't work, could you reproduce the problem with the developer console open (ctrl-shift-i), then save the console logs to disk, and upload?

**Comment by qqubes** [comment]
Here is a copypasta from the console section of the developer console:

> contentScript.js:187 [PHANTOM] error getting eth provider options
> contentScript.js:187 [PHANTOM] error updating cache Error: Something went wrong.
>     at SS.<anonymous> (contentScript.js:187:84324)
>     at Generator.next (<anonymous>)
>     at s (contentScript.js:187:83132)
> Markdown.ts:395 Uncaught (in promise) ReferenceError: Cannot access 'q' before initialization
>     at Object.J (Markdown.ts:395:5)
>     at _.start (ReadyWatchingStore.ts:38:30)
>     at get instance [as instance] (WidgetLayoutStore.ts:71:35)
>     at ./node_modules/matrix-react-sdk/src/stores/widgets/WidgetLayoutStore.ts (WidgetLayoutStore.ts:524:48)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/modules/ModuleRunner.ts (ModuleUiDialog.tsx:86:5)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/SecurityManager.ts (AccessSecretStorageDialog.tsx:454:5)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/MatrixClientPeg.ts (MatrixActionCreators.ts:378:5)
> Markdown.ts:395 Uncaught (in promise) ReferenceError: Cannot access 'q' before initialization
>     at Object.J (Markdown.ts:395:5)
>     at l.start (ReadyWatchingStore.ts:38:30)
>     at d.start (AsyncStoreWithClient.ts:48:31)
>     at WidgetMessagingStore.ts:38:18
>     at ./node_modules/matrix-react-sdk/src/stores/widgets/WidgetMessagingStore.ts (WidgetMessagingStore.ts:36:48)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/stores/ActiveWidgetStore.ts (shouldHideEvent.ts:83:1)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/stores/WidgetStore.ts (WidgetEchoStore.ts:118:1)
>     at u (bootstrap:19:32)
> Markdown.ts:395 Uncaught (in promise) ReferenceError: Cannot access 'q' before initialization
>     at Object.J (Markdown.ts:395:5)
>     at l.start (ReadyWatchingStore.ts:38:30)
>     at p.start (AsyncStoreWithClient.ts:48:31)
>     at WidgetStore.ts:56:18
>     at ./node_modules/matrix-react-sdk/src/stores/WidgetStore.ts (WidgetStore.ts:54:48)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/modules/ModuleRunner.ts (ModuleUiDialog.tsx:86:5)
>     at u (bootstrap:19:32)
>     at ./node_modules/matrix-react-sdk/src/SecurityManager.ts (AccessSecretStorageDialog.tsx:454:5)
>     at u (bootstrap:19:32)
> /config.app.element.…ter=1722259125267:1 
>  Failed to load resource: the server responded with a status of 404 ()
> rageshake.ts:77 Failed to open log database: UnknownError
> rageshake.ts:164 Uncaught (in promise) Error: Failed to open log database: UnknownError
>     at e.onerror (rageshake.ts:164:24)
> rageshake.ts:77 Error: Failed to open log database: UnknownError
>     at e.onerror (rageshake.ts:164:24)
> compat.ts:27 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
> rageshake.ts:77 startUpdater, current version is 1.11.71
> rageshake.ts:77 DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
> rageshake.ts:77 No update available, already on 1.11.71
> matrix-client.matrix…c2965/auth_issuer:1 
>  Failed to load resource: the server responded with a status of 404 ()
> rageshake.ts:77 StorageManager.idbLoad failed for account:mx_access_token 
> Event
﻿

**Comment by richvdh** [comment]
ok well, that didn't help much. I'm out of ideas.

**Comment by syserr0r** [comment]
In my case I had this on the windows x64 client immediately after installing an update that the client prompted me for.
To fix I re-installed the Windows client.

The console stack trace wasn't as long/detailed in my case - all I had at the top of the trace was `Cannot access 'q' before initialization`

**Comment by mohammadrafigh** [comment]
Yes, I faced it after upgrading element to the 2 recent versions. Here are the logs I get in console:

```
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:81507)
    at b.start (ReadyWatchingStore.ts:30:30)
    at get instance (WidgetLayoutStore.ts:63:35)
    at ./src/stores/widgets/WidgetLayoutStore.ts (WidgetLayoutStore.ts:518:48)
    at u (bootstrap:19:32)
    at ./src/utils/WidgetUtils.ts (init.js:1:1405739)
    at u (bootstrap:19:32)
    at ./src/stores/ActiveWidgetStore.ts (init.js:1:1193978)
    at u (bootstrap:19:32)
    at ./src/stores/WidgetStore.ts (init.js:1:1220711)
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:81507)
    at l.start (ReadyWatchingStore.ts:30:30)
    at d.start (AsyncStoreWithClient.ts:40:31)
    at WidgetMessagingStore.ts:30:18
    at ./src/stores/widgets/WidgetMessagingStore.ts (WidgetMessagingStore.ts:28:48)
    at u (bootstrap:19:32)
    at ./src/stores/ActiveWidgetStore.ts (init.js:1:1194012)
    at u (bootstrap:19:32)
    at ./src/stores/WidgetStore.ts (init.js:1:1220711)
    at u (bootstrap:19:32)
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:81507)
    at l.start (ReadyWatchingStore.ts:30:30)
    at p.start (AsyncStoreWithClient.ts:40:31)
    at WidgetStore.ts:48:18
    at ./src/stores/WidgetStore.ts (WidgetStore.ts:46:48)
    at u (bootstrap:19:32)
    at ./src/modules/ModuleRunner.ts (init.js:1:1107444)
    at u (bootstrap:19:32)
    at ./src/SecurityManager.ts (init.js:1:140738)
    at u (bootstrap:19:32)
rageshake.ts:69 emojibase MAX_EMOJI_VERSION 15
rageshake.ts:69 DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
Object.keys.forEach.e.<computed> @ rageshake.ts:69
matrix-client.matrix.org/_matrix/client/unstable/org.matrix.msc2965/auth_issuer:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```

**Comment by t3chguy** [comment]
@mohammadrafigh none of the errors in that log prevent the app from working. The ReferenceErrors are https://github.com/element-hq/element-web/issues/27606, the emoji version & deprecated config don't matter, and the 404 for auth_issuer just means your server isn't using OIDC-native, we can't hide 404 errors from web requests we make in a web browser.

**Comment by mohammadrafigh** [comment]
Sent full logs through app preferences referencing this issue

**Comment by richvdh** [comment]
Unfortunately nobody had time to look at the logs, and they have now expired.

I don't think it's a given that @mohammadrafigh was seeing the same problem as the OP. Since the OP has left the chat, I'm going to close this. If other people have similar problems, please open new issues.
