### ISSUE TITLE
Flaky Jest test: "AddRemoveThreepids › should add a phone number"

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28048]
```
  FAIL  test/components/views/settings/AddRemoveThreepids-test.tsx (12.174 s)
  ● AddRemoveThreepids › should add a phone number

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      187 |     });
      188 |
    > 189 |     it("should add a phone number", async () => {
          |     ^
      190 |         const onChangeFn = jest.fn();
      191 |         mocked(client.requestAdd3pidMsisdnToken).mockResolvedValue({
      192 |             sid: "1",

      at it (test/components/views/settings/AddRemoveThreepids-test.tsx:189:5)
      at Object.describe (test/components/views/settings/AddRemoveThreepids-test.tsx:40:1)
```

https://github.com/element-hq/matrix-react-sdk/actions/runs/10846560527/job/30099765623#step:7:4319

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/10851964582/job/30116914204

**Comment by richvdh** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/10852292938/job/30118002140

**Comment by richvdh** [comment]
Still an issue, but nobody has been reporting it :frowning_face:
