### ISSUE TITLE
error decrypting messages   [O-Frequent]

### ISSUE THREAD

**Issue by peteasa** [element-hq/element-web#28058]
### Steps to reproduce

get someone with possibly older version of client on android phone to send video clip

### Outcome

I expect to be able to see the video... but it is marked with red triangle and Error decrypting video

sent you initial debug log but it did not show the problem... so I attempted to download the video and message from debug log
2024-09-17T15:05:56.448Z W Unable to decrypt attachment

Note: also had same problem with my Android app (no logs - sorry)  Fix was to completely uninstall android element app and then re-install - now my Android app (now version 1.6.20, crypto version Rust SDK 0.7.0, Vodozemac 0.6.0) displays the videos

Note: this also occurred with other people in the chat group so I would like to mark this as O-Frequent because A it has occurred with 3 separate video clips from 2 separate people on 2 platforms (Android and Linux)

### Operating system

ubuntu

### Application version

Element version: 1.11.71

### How did you install the app?

apt install as per instructions at https://element.io/download#linux

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by richvdh** [comment]
```
2024-09-17T15:05:22.555Z W Unable to decrypt attachment:  MatrixError: [404] Not found (https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/DAVspLKibesLGUjNopnQfTYa?allow_redirect=true)
M_NOT_FOUND: MatrixError: [404] Not found (https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/DAVspLKibesLGUjNopnQfTYa?allow_redirect=true)
    at p (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:446534)
    at d (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:2737631)
    at async s.getFn (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:2755377)
    at async ft.componentDidMount (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:1942963)
```

Could you send a screenshot of what you're seeing, please?

**Comment by richvdh** [comment]
Actually nm, I reproduced it.

**Comment by richvdh** [comment]
Closing in favour of https://github.com/element-hq/element-web/issues/28060
