### ISSUE TITLE
Video thumbnails incorrectly report "Error decrypting video" for network errors

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28060]
Suppose the media repository is having a bad day, and returning 500 or 404 errors; or that the video you are looking for has been removed/was never correctly uploaded.

In that case, the following is shown in the timeline:

![image](https://github.com/user-attachments/assets/b59339ef-ccd8-42a4-8981-367c63f68159)

This is *not* a decryption error; instead it is a networking error. It should be caught and reported as such.

Related: https://github.com/element-hq/element-web/issues/27862, https://github.com/element-hq/element-web/issues/28016

**Comment by richvdh** [comment]
Console contains:

```
Unable to decrypt attachment:  DownloadError: NetworkError when attempting to fetch resource.
```

Other reports have the following in the logs:

```
2024-09-17T15:05:22.555Z W Unable to decrypt attachment:  MatrixError: [404] Not found (https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/DAVspLKibesLGUjNopnQfTYa?allow_redirect=true)
M_NOT_FOUND: MatrixError: [404] Not found (https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/DAVspLKibesLGUjNopnQfTYa?allow_redirect=true)
    at p (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:446534)
    at d (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:2737631)
    at async s.getFn (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:2755377)
    at async ft.componentDidMount (vector://vector/webapp/bundles/acaf93297a5a35ea8349/2586.js:2:1942963)
    ```

**Comment by karolyi** [comment]
Something's very off here. I can't upload any media with the synapse/element-web combo with my librewolf. Element-web v1.11.89, synapse 1.120.2

I don't even have an idea where to start searching for solutions. it seems the media upload gets canceled and is not available on the server storage. I get a 404 when manually trying to download the encrypted binary.

**Comment by t3chguy** [comment]
@karolyi librewolf is not a supported environment https://github.com/element-hq/element-web#supported-environments - it likely lacks required functionality support - in this case likely service workers

**Comment by karolyi** [comment]
@t3chguy service workers exist and are usable in librewolf, but can (and is suggested to) be disabled.

offtopic, but: how can a project claiming to be for privacy, not work on a browser that is for privacy? it kinda beats the purpose.

as it is now, I'm trying to upgrade my synapse to the latest version since it seems there is a newer version since mine. that needs a freebsd package update. by looking into the synapse logs, it seems there is an upload, but the file doesn't appear on the server. the media directory is created for it, but the media itself is not there.

**Comment by karolyi** [comment]
Apologies, but some concerns of mine are still valid. Since I've found a bug it seems, I'm opening a bugreport in synapse.

**Comment by Giwayume** [comment]
The same happens if the fetched mxc URI points to a thumbnail that is already an unencrypted image (not allowed via spec), or to any file that can't be decrypted. 

It would be best for resilience to treat loading the video thumbnail/poster from the video itself as two separate processes that can fail independently of each other.

If the video **can** be decrypted and the thumbnail cannot, just show a black empty video player that works when the user clicks the play button - or something along those lines.

**Comment by t3chguy** [comment]
iirc we don't download the video until you hit play otherwise you have a potentially huge video sat in memory even with no intention of playing it, so equally no way to test decrypting it until then

**Comment by Giwayume** [comment]
In this scenario, when you can't decrypt or download the thumbnail, you get this error

<img width="600" height="100" alt="Image" src="https://github.com/user-attachments/assets/d2d9cf42-0050-479a-8379-9bef3db7e34b" />

So even if the video would have decrypted and played just fine, the client doesn't allow the user to try, because it shows this error when it fails to load the thumbnail.
