### ISSUE TITLE
Timeline problems: jumping up and down and infinitely loading

### ISSUE THREAD

**Issue by dkasak** [element-hq/element-web#28067]
### Steps to reproduce

1. Enable `/jumptodate`
2. Join the Office of the Matrix.org Foundation
3. `/jumptodate 2024-09-01`
4. Try scrolling down. Notice frantic jumping of the timeline.
5. `/jumptodate 2024-09-02`
6. Try scrolling up. Notice infinite loading and slowdown.

#### What did you expect?

For the timeline to scroll, smoothly.

#### What happened instead?

It did not.

Some potentially related log snippets:

TimelinePanel.tsx:91 Uncaught TypeError: Cannot read properties of undefined (reading 'localTimestamp')
    at vd (TimelinePanel.tsx:91:18)
    at TimelinePanel.tsx:531:53
    at Vt (lodash.js:816:11)
    at $i (lodash.js:7372:14)
    at Object.onUnfillRequest (TimelinePanel.tsx:531:19)
    at ScrollPanel.tsx:469:17

rageshake.ts:77 RangeError: Invalid array length
    at Array.push (<anonymous>)
    at L.getEvents (timeline-window.ts:421:24)
    at _d.getEvents (TimelinePanel.tsx:1696:49)
    at TimelinePanel.tsx:627:49

### Operating system

Arch Linux

### Application version

Element version: 1.11.75 Crypto version: Rust SDK 0.7.1 (c8c9d15), Vodozemac 0.6.0

### How did you install the app?

Arch Linux repo

### Will you send logs?

Yes

**Comment by rda0** [comment]
I also notice this all the time when using the search function:

1. Search something
2. Click on some old message
3. Start scrolling down. Notice frantic jumping of the timeline (I think mostly jumping up in that case).

- Sometimes it was fully stuck on some timeline position, which was impossible to scroll over.
- Sometimes I was able to fix/improve it by clear/cache and reload

Sending logs...

**Comment by simonmichael** [comment]
Me too - I have seen this occasionally for a long time, eg today in Element Desktop Nightly on mac, I could not scroll through the last two days of backlog in a room, it kept jumping confusingly backward at a certain point. Later it stopped doing that.

I did have Jump to date enabled in Settings > Labs. Probably not the cause, but I'll turn it off for a while to see if it makes any difference.

**Comment by mepholic** [comment]
This is probably related to the many other scrolling related issues as seen in #28522 #28374 #28390

This random jumping around and flashing could be extremely dangerous for someone with photosensitive epilepsy and I recommend that warnings be put on the app until these UI issues are fixed.

**Comment by twassman** [comment]
Experiencing something facially similar after jumping to a message from search results, on Element Desktop 1.12.6 — when trying to scroll up, the timeline instead repeatedly jumps back down, with the uppermost messages rapidly blinking in and out of existence. Would prefer not to show video of my actual chat logs, but the scroll-bar looks like this:


https://github.com/user-attachments/assets/e690b23d-473e-4322-a6ce-080f5eca50b1

**Comment by onmyouji** [comment]
I also experienced the same thing on Firefox.

OS: Windows 10 22H2
Browser: Firefox 147.0.3
Element version: 1.12.9
Crypto version: Rust SDK 0.16.0 (95b5e83), Vodozemac 0.9.0
