### ISSUE TITLE
Flaky jest test: `<MatrixChat /> › mobile registration › should render mobile registration`

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28122]
```
  FAIL  test/components/structures/MatrixChat-test.tsx (54.373 s)
  ● <MatrixChat /> › mobile registration › should render mobile registration

    TypeError: prop.startsWith is not a function

      116 |     const inlineStyleProps = Object.values(document.body.style);
      117 |     for (const prop of inlineStyleProps) {
    > 118 |         if (prop.startsWith("--")) {
          |                  ^
      119 |             document.body.style.removeProperty(prop);
      120 |         }
      121 |     }

      at startsWith (src/theme.ts:118:18)
      at clearCustomTheme (src/theme.ts:272:5)
      at ThemeWatcher.recheck (src/settings/watchers/ThemeWatcher.ts:80:21)
      at MatrixChat.recheck [as viewWelcome] (src/components/structures/MatrixChat.tsx:1103:27)
      at viewWelcome (src/components/structures/MatrixChat.tsx:801:22)
      at MatrixDispatcher.invokeCallback (src/dispatcher/dispatcher.ts:112:31)
      at invokeCallback (src/dispatcher/dispatcher.ts:89:22)
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:520:19)
```

https://github.com/element-hq/matrix-react-sdk/actions/runs/11103597649/job/30845884471#step:7:4500

**Comment by richvdh** [comment]
https://github.com/element-hq/matrix-react-sdk/actions/runs/11109355204/job/30864508362?pr=104
