### ISSUE TITLE
Migrate away from Yarn 1

### ISSUE THREAD

**Issue by dbkr** [element-hq/element-web#28146]
### Your use case

Somehow I don't think we had an issue for migrating away from yarn 1. Here is one.

 * Yarn 1 is now old & replaced by Yarn 2
 * Yarn has bugs like https://github.com/eslint/eslint/discussions/17215#discussioncomment-6511704

We could upgrade to yarn 2 although I don't really see the point: it's about as much effort to move to something better. npm is fine nowadays. I believe pnpm is also fine, although doesn't tend to come as standard on github actions runners etc.

Opinions welcome on what to move to.

**Comment by robintown** [comment]
Something that would become an issue if this project migrated to Yarn Berry is that you cannot `yarn link` local packages without causing package.json and yarn.lock to be modified. (https://github.com/yarnpkg/berry/issues/4870) I tried out a [workaround](https://github.com/element-hq/element-call/pull/3095/commits/0b26dc2f43485c145ec177e032d7ad3f7053fb99) in Element Call using a Yarn plugin, but the plugin still modifies yarn.lock.

**Comment by aerusso** [comment]
I'm trying to build this with yarn 4 (in debian testing), and the build fails with

<details>

  <summary>`yarn build` error message</summary>

```
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '@vector-im/matrix-wysiwyg-wasm' in '/build/element-web/node_modules/@vector-im/matrix-wysiwyg/dist'
    at /build/element-web/node_modules/webpack/lib/Compilation.js:2123:28
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:923:13
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:339:22
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:520:22
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:151:10
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:783:25
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:1008:8
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:1137:5
    at /build/element-web/node_modules/neo-async/async.js:6883:13
    at /build/element-web/node_modules/webpack/lib/NormalModuleFactory.js:1120:45
    at finishWithoutResolve (/build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:567:11)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:656:15
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/forEachBail.js:39:13
    at /build/element-web/node_modules/enhanced-resolve/lib/AliasPlugin.js:177:14
    at next (/build/element-web/node_modules/enhanced-resolve/lib/forEachBail.js:35:3)
    at forEachBail (/build/element-web/node_modules/enhanced-resolve/lib/forEachBail.js:49:9)
    at /build/element-web/node_modules/enhanced-resolve/lib/AliasPlugin.js:62:5
    at _next0 (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:89:43
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:40:47
    at _next0 (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:87:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:53:42
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/Resolver.js:718:5
    at eval (eval at create (/build/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /build/element-web/node_modules/enhanced-resolve/lib/FileExistsPlugin.js:38:14
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
resolve '@vector-im/matrix-wysiwyg-wasm' in '/build/element-web/node_modules/@vector-im/matrix-wysiwyg/dist'
  Parsed request is a module
  using description file: /build/element-web/node_modules/@vector-im/matrix-wysiwyg/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /build/element-web/node_modules/@vector-im/matrix-wysiwyg/dist/node_modules doesn't exist or is not a directory
      looking for modules in /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules
        single file module
          using description file: /build/element-web/node_modules/@vector-im/matrix-wysiwyg/package.json (relative path: ./node_modules/@vector-im/matrix-wysiwyg-wasm)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm.json doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm.tsx doesn't exist
        /build/element-web/node_modules/@vector-im/matrix-wysiwyg/node_modules/@vector-im/matrix-wysiwyg-wasm doesn't exist
      /build/element-web/node_modules/@vector-im/node_modules doesn't exist or is not a directory
      /build/element-web/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /build/element-web/node_modules
        single file module
          using description file: /build/element-web/package.json (relative path: ./node_modules/@vector-im/matrix-wysiwyg-wasm)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm.json doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm.tsx doesn't exist
        /build/element-web/node_modules/@vector-im/matrix-wysiwyg-wasm doesn't exist
      /build/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
```

</details>

This is after `apt install yarnpkg nodejs npm`.

I was actually quite impressed that Debian was AHEAD of the requirements on literally any project!

In any case, I can't tell if this is just because I'm doing something obviously wrong (I'm not a Javascript developer), or if this is a backwards-incompatible change in yarn.

It seems to me that `matrix-wysiwyg-wasm` is referencing something by relative path in yarn.lock (`"@vector-im/matrix-wysiwyg-wasm@link:../../../.cache` ).  I don't know if that's relevant or not, but it just happened to stand out.

Maybe that dependent package isn't forward compatible with yarn 4?  But, perhaps moving to something that provides a more stable interface is a better use of resources.

**Comment by t3chguy** [comment]
Yes, Yarn v4 is inherently not backwards compatible with Yarn Classic (v1) - we do link to the yarn classic install guide https://github.com/element-hq/element-web#building-from-source for a reason.

**Comment by t3chguy** [comment]
Done
