### ISSUE TITLE
Impossible to continue after "Element is open in another window"

### ISSUE THREAD

**Issue by Xzensi** [element-hq/element-web#28168]
### STR

1. Have element-desktop (or web, I guess) running
2. Unclean shutdown (eg reboot)
3. Wind clock back by 5 minutes or so
4. Start Element again
5. Observe "Element is open in another window" dialog:
![image](https://github.com/user-attachments/assets/a10e6418-63f8-4192-b226-00469aeffd22)
6. Click continue
7. Observe spinner:
![image](https://github.com/user-attachments/assets/401ddf26-fd28-45f1-88c0-44e340688c80)
8. Wait for clock to pass the time of the unclean shutdown
9. Element loads at last

# Original description follows

### Steps to reproduce

Element worked fine. Rebooted Windows 10, suddenly get "Element is open in another window" warning even though I do not have any other client open. Pressing "Continue" does nothing and loads forever.

I tried:
- Reinstalling Element desktop
- At /synapse-admin I removed myself under "DEVICES"

Web and mobile clients still work fine.

#### What did you expect?
Being able to just use Element like normal.

#### What happened instead?
![image](https://github.com/element-hq/element-web/assets/14015478/c77b9449-ce45-4bee-af9a-d4c427d19416)

### Operating system

Windows 10

### Application version

Latest, reinstalled fresh

### How did you install the app?

https://element.io/download

### Will you send logs?

No

**Comment by kosmos** [comment]
I get the same error in the console as @1a11 :

```
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:77347)
    at b.start (ReadyWatchingStore.ts:30:30)
    at get instance (WidgetLayoutStore.ts:63:35)
    at ./src/stores/widgets/WidgetLayoutStore.ts (WidgetLayoutStore.ts:518:48)
    at l (bootstrap:19:32)
    at ./src/utils/WidgetUtils.ts (init.js:1:1399311)
    at l (bootstrap:19:32)
    at ./src/stores/ActiveWidgetStore.ts (init.js:1:1186380)
    at l (bootstrap:19:32)
    at ./src/stores/WidgetStore.ts (init.js:1:1213116)
J @ init.js:1
start @ ReadyWatchingStore.ts:30
get instance @ WidgetLayoutStore.ts:63
./src/stores/widgets/WidgetLayoutStore.ts @ WidgetLayoutStore.ts:518
l @ bootstrap:19
./src/utils/WidgetUtils.ts @ init.js:1
l @ bootstrap:19
./src/stores/ActiveWidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/stores/WidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/modules/ModuleRunner.ts @ init.js:1
l @ bootstrap:19
./src/SecurityManager.ts @ init.js:1
l @ bootstrap:19
./src/MatrixClientPeg.ts @ init.js:1
l @ bootstrap:19
./src/settings/controllers/DeviceIsolationModeController.ts @ init.js:1
l @ bootstrap:19
./src/settings/Settings.tsx @ init.js:1
l @ bootstrap:19
./src/settings/SettingsStore.ts @ init.js:1
l @ bootstrap:19
./src/languageHandler.tsx @ init.js:1
l @ bootstrap:19
./src/vector/init.tsx @ init.js:1
l @ bootstrap:19
Promise.then
(anonymous) @ index.ts:119
./src/vector/index.ts @ index.ts:259
l @ bootstrap:19
(anonymous) @ startup:4
l.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ startup:5
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:77347)
    at l.start (ReadyWatchingStore.ts:30:30)
    at d.start (AsyncStoreWithClient.ts:40:31)
    at WidgetMessagingStore.ts:30:18
    at ./src/stores/widgets/WidgetMessagingStore.ts (WidgetMessagingStore.ts:28:48)
    at l (bootstrap:19:32)
    at ./src/stores/ActiveWidgetStore.ts (init.js:1:1186414)
    at l (bootstrap:19:32)
    at ./src/stores/WidgetStore.ts (init.js:1:1213116)
    at l (bootstrap:19:32)
J @ init.js:1
start @ ReadyWatchingStore.ts:30
start @ AsyncStoreWithClient.ts:40
(anonymous) @ WidgetMessagingStore.ts:30
./src/stores/widgets/WidgetMessagingStore.ts @ WidgetMessagingStore.ts:28
l @ bootstrap:19
./src/stores/ActiveWidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/stores/WidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/modules/ModuleRunner.ts @ init.js:1
l @ bootstrap:19
./src/SecurityManager.ts @ init.js:1
l @ bootstrap:19
./src/MatrixClientPeg.ts @ init.js:1
l @ bootstrap:19
./src/settings/controllers/DeviceIsolationModeController.ts @ init.js:1
l @ bootstrap:19
./src/settings/Settings.tsx @ init.js:1
l @ bootstrap:19
./src/settings/SettingsStore.ts @ init.js:1
l @ bootstrap:19
./src/languageHandler.tsx @ init.js:1
l @ bootstrap:19
./src/vector/init.tsx @ init.js:1
l @ bootstrap:19
await in l
(anonymous) @ WidgetMessagingStore.ts:30
./src/stores/widgets/WidgetMessagingStore.ts @ WidgetMessagingStore.ts:28
l @ bootstrap:19
./src/stores/ActiveWidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/stores/WidgetStore.ts @ init.js:1
l @ bootstrap:19
./src/modules/ModuleRunner.ts @ init.js:1
l @ bootstrap:19
./src/SecurityManager.ts @ init.js:1
l @ bootstrap:19
./src/MatrixClientPeg.ts @ init.js:1
l @ bootstrap:19
./src/settings/controllers/DeviceIsolationModeController.ts @ init.js:1
l @ bootstrap:19
./src/settings/Settings.tsx @ init.js:1
l @ bootstrap:19
./src/settings/SettingsStore.ts @ init.js:1
l @ bootstrap:19
./src/languageHandler.tsx @ init.js:1
l @ bootstrap:19
./src/vector/init.tsx @ init.js:1
l @ bootstrap:19
Promise.then
(anonymous) @ index.ts:119
./src/vector/index.ts @ index.ts:259
l @ bootstrap:19
(anonymous) @ startup:4
l.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ startup:5
init.js:1 Uncaught (in promise) ReferenceError: Cannot access 'V' before initialization
    at Object.J (init.js:1:77347)
    at l.start (ReadyWatchingStore.ts:30:30)
    at p.start (AsyncStoreWithClient.ts:40:31)
    at WidgetStore.ts:48:18
    at ./src/stores/WidgetStore.ts (WidgetStore.ts:46:48)
    at l (bootstrap:19:32)
    at ./src/modules/ModuleRunner.ts (init.js:1:1099717)
    at l (bootstrap:19:32)
    at ./src/SecurityManager.ts (init.js:1:135166)
    at l (bootstrap:19:32)
```

Do you know what could be causing it?

**Comment by Mr-Pearce** [comment]
Had the same Problem.
I had to make a testcase where i had to set the computer clock manually a few days into the future.
After setting the clock back today, my element wouldn't start anymore.
I Had to Uninstall and delete all caches for it to run again.

**Comment by richvdh** [comment]
I haven't forgotten about this, I just haven't found time to come back and fix it.

The problem is that the "last ping time" from the other session is set in the future, so the new session thinks it's still alive despite us telling it we want to steal the lock. I think the solution is that, if we find the "last ping time" is in the future, to check if it is still *changing* once we've sent the memo, and if not, assume that (a) it is dead, (b) someone wound back the clock.

**Comment by richvdh** [comment]
> I get the same error in the console as @1a11 :

unrelated: it's https://github.com/element-hq/element-web/issues/27606
