### ISSUE TITLE
Flaky Jest test: `AddRemoveThreepids › should display an error if the code is incorrect`

### ISSUE THREAD

**Issue by richvdh** [element-hq/element-web#28160]
```
 FAIL  test/components/views/settings/AddRemoveThreepids-test.tsx (13.309 s)
  ● AddRemoveThreepids › should display an error if the code is incorrect

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      255 |     });
      256 |
    > 257 |     it("should display an error if the code is incorrect", async () => {
          |     ^
      258 |         const onChangeFn = jest.fn();
      259 |         const createDialogFn = jest.spyOn(Modal, "createDialog");
      260 |         mocked(client.requestAdd3pidMsisdnToken).mockResolvedValue({

      at it (test/components/views/settings/AddRemoveThreepids-test.tsx:257:5)
      at Object.describe (test/components/views/settings/AddRemoveThreepids-test.tsx:40:1)
```

https://github.com/matrix-org/matrix-js-sdk/actions/runs/11214479864/job/31169646143

**Comment by dbkr** [comment]
We decided we probably ought tio port this to a playwright test if we can't de-flake it.
