### ISSUE TITLE
Error getting encryption info on event, missing field `ciphertext` at line 1 column 160

### ISSUE THREAD

**Issue by rda0** [element-hq/element-web#32070]
### Steps to reproduce

1. Ctrl-F in e2ee DM
2. Enter `foo` + ENTER
3. It starts showing search results for a few milliseconds and switches back to showing the normal timeline

### Outcome

This only happens in some rooms. I just completely regenerated the message search index, but it did not help.

Console output:

```
Error getting encryption info on event $event in room !roomid:phys.ethz.ch Error: missing field `ciphertext` at line 1 column 160
    at A.exports.__wbindgen_error_new (￼index.js:10209:17)
    at matrix_sdk_crypto_wasm.wasm.<T as futures_util::fns::FnOnce1<A>>::call_once::h008e54b08a4a32ec (￼matrix_sdk_crypto_wa…m-019abe36:0x3ccd85)
    at matrix_sdk_crypto_wasm.wasm.matrix_sdk_crypto_wasm::future::future_to_promise_with_custom_error::{{closure}}::{{closure}}::h75f7cb07f34e6b9a (￼matrix_sdk_crypto_wa…m-019abe36:0x1d9aeb)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::h22ec0e9d9c410ff8 (￼matrix_sdk_crypto_wa…m-019abe36:0x30c5cf)
    at matrix_sdk_crypto_wasm.wasm.<dyn core::ops::function::FnMut<(￼webapp/A,)>+Output =…_wasm.wasm-019abe36)
    at l (￼index.js:261:10)
    at E (￼index.js:203:20)
```

### Operating system

Linux Debian 12

### Application version

D-PHYS Element Labs rda version: 1.11.84 Crypto version: Rust SDK 0.7.2 (517d99b), Vodozemac 0.7.0

### How did you install the app?

debian package

### Homeserver

Synapse 1.118.0

### Will you send logs?

Yes

**Comment by richvdh** [comment]
I was unable to reproduce this. I suspect it's been fixed along the way. If it happens again, please send logs again and we can reopen.
